"""empty message

Revision ID: 11695d7a36d5
Revises: 
Create Date: 2022-08-01 16:11:17.930991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11695d7a36d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('bedroom', sa.Integer(), nullable=True),
    sa.Column('liv', sa.Integer(), nullable=True),
    sa.Column('bath', sa.Integer(), nullable=True),
    sa.Column('gar', sa.Integer(), nullable=True),
    sa.Column('gar_price', sa.Integer(), nullable=True),
    sa.Column('house_age', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floor_all', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('land_use', sa.String(length=30), nullable=True),
    sa.Column('material', sa.String(length=30), nullable=True),
    sa.Column('org', sa.String(length=30), nullable=True),
    sa.Column('predict_result', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('predict_result')
    op.drop_index('email', table_name='test_table')
    op.drop_index('name', table_name='test_table')
    op.drop_table('test_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'test_table', ['name'], unique=False)
    op.create_index('email', 'test_table', ['email'], unique=False)
    op.create_table('predict_result',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=30), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('region', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True),
    sa.Column('bedroom', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('livingroom', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bathroom', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predict_result', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parking', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('price_result')
    # ### end Alembic commands ###
