"""empty message

Revision ID: 24ec4b44df19
Revises: 5a29aa3768c1
Create Date: 2022-08-01 19:17:27.942241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24ec4b44df19'
down_revision = '5a29aa3768c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_result', 'gar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_result', sa.Column('gar', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
