"""update1

Revision ID: 2ba5521a383d
Revises: e231a2f2a801
Create Date: 2022-08-05 00:26:37.072237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba5521a383d'
down_revision = 'e231a2f2a801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('fengshui1', sa.String(length=3), nullable=True),
    sa.Column('fengshui2', sa.String(length=3), nullable=True),
    sa.Column('fengshui3', sa.String(length=3), nullable=True),
    sa.Column('images_origin', sa.String(length=200), nullable=True),
    sa.Column('images_result', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
