"""empty message

Revision ID: 5a29aa3768c1
Revises: 11695d7a36d5
Create Date: 2022-08-01 19:08:23.773417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a29aa3768c1'
down_revision = '11695d7a36d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_result', sa.Column('house_type', sa.String(length=30), nullable=True))
    op.add_column('price_result', sa.Column('house', sa.String(length=30), nullable=True))
    op.drop_column('price_result', 'land_use')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_result', sa.Column('land_use', mysql.VARCHAR(collation='utf8mb4_general_ci', length=30), nullable=True))
    op.drop_column('price_result', 'house')
    op.drop_column('price_result', 'house_type')
    # ### end Alembic commands ###
