"""update

Revision ID: e231a2f2a801
Revises: 98f2435e681d
Create Date: 2022-08-04 23:12:51.073997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e231a2f2a801'
down_revision = '98f2435e681d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('fengshui1', sa.String(length=3), nullable=True))
    op.add_column('images', sa.Column('fengshui2', sa.String(length=3), nullable=True))
    op.add_column('images', sa.Column('fengshui3', sa.String(length=3), nullable=True))
    op.add_column('images', sa.Column('images_origin', sa.String(length=200), nullable=True))
    op.add_column('images', sa.Column('images_result', sa.String(length=200), nullable=True))
    op.drop_column('images', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('images', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True))
    op.drop_column('images', 'images_result')
    op.drop_column('images', 'images_origin')
    op.drop_column('images', 'fengshui3')
    op.drop_column('images', 'fengshui2')
    op.drop_column('images', 'fengshui1')
    # ### end Alembic commands ###
